### PR TITLE
Aci filter entry

### PR DESCRIPTION
**Pull request by jmcgill298**

### CODE REVIEW

**Comment by jmcgill298** [comment]
@schunduri @dagwieers 

I have two modules in for supporting check_mode and handling parameters with null values. What do you all think about my approach?

**Comment by dagwieers** [comment]
Looking good. Not sure if this would cover all bases yet.
But we're going to keep it :-) I have some cosmetic and code changes I would like to do, the review process is too hard for that. I added some notes to the first PR already.

**Comment by jmcgill298** [comment]
@dagwieers I implemented the changes you requested, but a coupld of notes

1) aci.payload() works for simplest case, which works for modules I've updated so far. aci.payload() will be fleshed out when I get to work on the aci_bridge_domain module to handle the child_configs argument. I believe this should be simple enough to get working though.

2) The get/post/delete_config() methods are ugly and need to be reworked. Most of it is copying from the original request method, and making a few adjustments to work in the new format. Given the time constraints and amount of work, I have put this as a low priority as they seem to do all the right things; they just would benefit from splitting the complexity into multiple methods.

**Comment by jmcgill298** [comment]
@dagwieers I can't assign labels, but this should not be merged at least until there is a subnet module. I wanted to give you a chance to see a solution for child objects, which I have done with updated aci.diff(), aci.payload(), and the aci_bridge_domain module. I know it isn't the nicest code, but I am tired and just wanted to get the base method out there for you to see

**Comment by dagwieers** [comment]
Thanks, we'll merge this and integrate with existing modules.

**Pull request merged**
