### PR TITLE
Child configs bugfix

### PR DESCRIPTION
**Pull request by qzx**
Hi,

I found this bug in the aci.py. I see it has happened before mentioned in:
https://github.com/networktocode/ntc-misc/issues/9

The patch for this seems to have been to create a copy of the dictionary and loop over the copied keys. This however is still not working properly and still returning same RuntimeError (dictionary changed size during iteration).

Instead of using a copy (with some references) we could instead add the keys to a list and remove them from the dictionary only if we actually intend to use it (if has_value is True)

### CODE REVIEW

**Comment by dagwieers** [comment]
The problem here is that you need to copy child_configs, not the child. And iterate over the copy, while changing the original. That should work fine.

**Comment by jmcgill298** [comment]
I have no errors when running in python3.6.2 environment

**Comment by jmcgill298** [comment]
interesting that Ansible says it is using module in python3.6.2, but I do not get the error. But I do see the issue still when using the interpreter.

**Comment by jmcgill298** [comment]
using deepcopy should fix it instead of copy: `child_copy = child.copy()` changes to `child_copy = deepcopy(child)`

**Pull request closed without merging**
