### PR TITLE
Update README and remove everything

### PR DESCRIPTION
**Pull request by dagwieers**
With the upcoming release of Ansible v2.5 we don't want people to use this repository. And while removing the repository is probably detrimental to our goals, removing everything except the modules and the README will ensure people don't stick around (or take this repository as the authoritative source).

So this PR is removing everything except the actual modules, and replaces the README with a statement where to find the official modules, and links to: https://docs.ansible.com/ansible/devel/scenario_guides/guide_aci.html and https://github.com/ansible/community/wiki/Network:-ACI

Shout out if this is contrary to what you think needs to happen :-) #

### CODE REVIEW

**Comment by dagwieers** [comment]
We could also update the modules with the modules that ship with v2.5, however it is likely that these modules will fail to work on Ansible v2.4 and older. So I don't see the point in doing this.

**Comment by dagwieers** [comment]
cc @nilloBE

**Comment by rsmeyers** [comment]
I would drop everything and point in the main file to the Ansible project, else it's gonna be confusing what is here and how to use it...., as it's actually already part of Ansible...

**Comment by dagwieers** [comment]
@rsmeyers I know there used to be some concerns (by @devarshishah3 and @schunduri) with existing users of this repository that would break their setup if they run `git pull`.

Ultimately the question is whether it's good practice to keep on using this repository, but if they are using older Ansible versions (older than v2.4), there would not be an alternative...

**Comment by dagwieers** [comment]
@rsmeyers Ok, I have removed the modules now as well.

**Pull request merged**
