### PR TITLE
aci_action_rule_profile: Refactor

### PR DESCRIPTION
**Pull request by dagwieers**
Please review.

### CODE REVIEW

**Comment by jmcgill298** [comment]
@dagwieers I am not one of the approvers for this

**Comment by dagwieers** [comment]
@jmcgill298 Does it matter ? I assumed everyone could review.

**Comment by jmcgill298** [comment]
It does seem to matter; I did not have a review button earlier.

**Comment by dagwieers** [comment]
Update is fine. Thanks !

**Pull request merged**
