### PR TITLE
aci_bd_subnet: Improve support for multiple scope options

### LINKED ISSUE #162: In aci_bd_subnet, 'scope' needs to support multiple parameters at once
The module aci_bd_subnet has an attribute 'scope' that allows to specify if a subnet should be kept private to a VRF, or if it should be advertised and potentially shared. There are therefore three options: public, private and shared. Public and Private are mutually exclusive, but 'shared' can be present with either of them. 

We need to add the possibility of adding:

scope: "public,shared"
or
scope: "private,share"

in addition to public and private being the only setting.

### PR DESCRIPTION
**Pull request by dagwieers**
This patch supports combinations of private/public with shared as values
for the scope parameter. The input now is defined as a list, which means
Ansible will accept either a comma-separated list, or a proper JSON/YAML
list definition.

The code ensures that private and public are mutually exclusive, and it
also checks for unknown options.

This fixes #162

### CODE REVIEW

**Comment by dagwieers** [comment]
In PR https://github.com/ansible/ansible/pull/31637 I added the feature for Ansible v2.5 that allows a set of choices for a list-type parameter.

**Comment by dagwieers** [comment]
@jmcgill298 @schunduri Any feedback ?

**Comment by jmcgill298** [comment]
@dagwieers I'm working on moving the brackets ([]) out of the URL building in module_utils to modules (only 3 actually require them). The reason for this is that the pool module (vlan, vxlan, vsan) require that only part of the URL be in brackets, and [path/data-[inner bracket]] does not work. One of the modules that I need to modify for this to work is the `aci_bd_subnet` module, so I will work on a solution that meets my comments per above. I already have this done, just working on some integration tests for all three modules.

**Comment by dagwieers** [comment]
No longer required.

**Pull request closed without merging**
